#!/usr/bin/env sh

GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m'

echo
echo -e "${GREEN}Updating ${BLUE}$(hostname)${GREEN}...${NC}"
echo

# build firefox before running
guix build firefox --substitute-urls='https://ci.guix.gnu.org https://bordeaux.guix.gnu.org https://substitutes.nonguix.org'

GUIX_TARGET=home guix home reconfigure -L ~/.dotfiles ~/.dotfiles/polterguix/systems/$(hostname).scm
