#!/usr/bin/env sh

GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m'

echo
echo -e "${GREEN}Updating ${BLUE}$(hostname)${GREEN}...${NC}"
echo

GUIX_TARGET=system sudo guix system reconfigure -L /home/pol/.dotfiles ~/.dotfiles/polterguix/systems/$(hostname).scm
